---
inputfile: temp.log
startdate: /15\/Nov\/2017/
enddate:
overtime: 1
topip: 10
toprequest: 10
logformat: '$remote_addr |$remote_port |$request_time |$remote_user |$time_local |$request |$status |$body_bytes_sent |$http_referer |$http_user_agent'
truncatedatabase: true
developermap: {

              }
emailmap: {

}
emailconfig:
  sending: true
  username: ''
  password: ''
  smtphost: ''
  sender: ''
  sendername: ''
  subject: ''
  body: ''
  receivers:
    - ''
  cc:
    - ''
