---
inputfile: temp.log
startdate: /29\/Sep\/2017/
enddate:
overtime: 5
topip: 10
toprequest: 10
logformat: '$remote_addr|$remote_port|$request_time|$remote_user|$time_local|$request|$status|$body_bytes_sent|$http_referer|$http_user_agent'
truncatedatabase: true
